[package]
authors = ['Parami Devs <info@parami.io>']
description = 'Parami Dana Runtime.'
edition = '2021'
homepage = 'https://parami.io'
license = 'GPL-3.0-only WITH Classpath-exception-2.0'
name = 'parami-dana-runtime'
publish = false
repository = 'https://github.com/parami-protocol/parami-blockchain/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies.substrate-wasm-builder]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.13'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.2.0'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '1.0'

[dependencies]
hex-literal = { version = '0.3', optional = true }
serde = { version = '1.0', optional = true, features = ['derive'] }

# Local Dependencies
parami-primitives = { path = '../../primitives', default-features = false }
parami-ad = { path = '../../pallets/ad', default-features = false }
parami-advertiser = { path = '../../pallets/advertiser', default-features = false }
parami-chainbridge = { path = '../../pallets/chainbridge', default-features = false }
parami-xassets = { path = '../../pallets/xassets', default-features = false }
parami-did = { path = '../../pallets/did', default-features = false }
parami-linker = { path = '../../pallets/linker', default-features = false }
parami-magic = { path = '../../pallets/magic', default-features = false }
parami-nft = { path = '../../pallets/nft', default-features = false }
parami-ocw = { path = '../../pallets/ocw', default-features = false }
parami-swap = { path = '../../pallets/swap', default-features = false }
parami-swap-rpc-runtime-api = { path = '../../pallets/swap/rpc/runtime-api', default-features = false }
parami-tag = { path = '../../pallets/tag', default-features = false }
parami-traits = { path = '../../pallets/traits', default-features = false }

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-inherents = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-npos-elections = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-offchain = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-session = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-staking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
sp-version = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }

## Substrate FRAME Dependencies
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', default-features = false, optional = true, branch = 'polkadot-v0.9.13' }
frame-election-provider-support = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
frame-executive = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
frame-support = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate', default-features = false, optional = true, branch = 'polkadot-v0.9.13' }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }

## Substrate Pallet Dependencies
pallet-assets = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-authority-discovery = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-bounties = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-collective = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-contracts = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-contracts-primitives = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-contracts-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-democracy = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-election-provider-multi-phase = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-elections-phragmen = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-im-online = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-membership = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-mmr = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-multisig = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-offences = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-recovery = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-scheduler = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-session = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-session-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false, optional = true }
pallet-society = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-staking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-staking-reward-curve = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-sudo = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-tips = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-treasury = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-uniques = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-utility = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }
pallet-vesting = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }

[features]
default = ['std']

std = [
    'codec/std',
    'serde',
    'scale-info/std',

    'parami-primitives/std',
    'parami-ad/std',
    'parami-advertiser/std',
    'parami-chainbridge/std',
    'parami-xassets/std',
    'parami-did/std',
    'parami-linker/std',
    'parami-magic/std',
    'parami-nft/std',
    'parami-ocw/std',
    'parami-swap/std',
    'parami-swap-rpc-runtime-api/std',
    'parami-tag/std',
    'parami-traits/std',

    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-npos-elections/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',

    'frame-election-provider-support/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',

    'pallet-assets/std',
    'pallet-aura/std',
    'pallet-authority-discovery/std',
    'pallet-authorship/std',
    'pallet-balances/std',
    'pallet-bounties/std',
    'pallet-collective/std',
    'pallet-contracts-primitives/std',
    'pallet-contracts-rpc-runtime-api/std',
    'pallet-contracts/std',
    'pallet-democracy/std',
    'pallet-election-provider-multi-phase/std',
    'pallet-elections-phragmen/std',
    'pallet-grandpa/std',
    'pallet-im-online/std',
    'pallet-membership/std',
    'pallet-mmr/std',
    'pallet-multisig/std',
    'pallet-offences/std',
    'pallet-randomness-collective-flip/std',
    'pallet-recovery/std',
    'pallet-scheduler/std',
    'pallet-session/std',
    'pallet-society/std',
    'pallet-staking/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-tips/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-transaction-payment/std',
    'pallet-treasury/std',
    'pallet-uniques/std',
    'pallet-utility/std',
    'pallet-vesting/std',
]

runtime-benchmarks = [
    'hex-literal',

    'parami-ad/runtime-benchmarks',
    'parami-advertiser/runtime-benchmarks',
    'parami-chainbridge/runtime-benchmarks',
    'parami-xassets/runtime-benchmarks',
    'parami-did/runtime-benchmarks',
    'parami-linker/runtime-benchmarks',
    'parami-nft/runtime-benchmarks',
    'parami-swap/runtime-benchmarks',
    'parami-tag/runtime-benchmarks',

    'sp-runtime/runtime-benchmarks',

    'frame-benchmarking',
    'frame-system-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'frame-election-provider-support/runtime-benchmarks',

    'pallet-assets/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-bounties/runtime-benchmarks',
    'pallet-collective/runtime-benchmarks',
    'pallet-contracts/runtime-benchmarks',
    'pallet-democracy/runtime-benchmarks',
    'pallet-election-provider-multi-phase/runtime-benchmarks',
    'pallet-elections-phragmen/runtime-benchmarks',
    'pallet-grandpa/runtime-benchmarks',
    'pallet-im-online/runtime-benchmarks',
    'pallet-membership/runtime-benchmarks',
    'pallet-mmr/runtime-benchmarks',
    'pallet-multisig/runtime-benchmarks',
    'pallet-offences/runtime-benchmarks',
    'pallet-scheduler/runtime-benchmarks',
    'pallet-session-benchmarking',
    'pallet-society/runtime-benchmarks',
    'pallet-staking/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'pallet-tips/runtime-benchmarks',
    'pallet-treasury/runtime-benchmarks',
    'pallet-uniques/runtime-benchmarks',
    'pallet-utility/runtime-benchmarks',
    'pallet-vesting/runtime-benchmarks',
]
